spin_manifest_version = 2

[application]
name = "example"
version = "0.1.0"
description = "A simple HTTP handler"

[[trigger.http]]
route = "/..."
component = "example"

[component.example]
source = "service.wasm"
#source = "target/wasm32-wasi/release/example.wasm"
sqlite_databases = ["default"]
[component.example.build]
command = "./build.sh"
