spin_manifest_version = 2

[application]
authors = ["Ryan Levick <me@ryanlevick.com>"]
description = "A todo application written in spin"
name = "todo"
version = "0.1.0"

[[trigger.http]]
route = "/api/..."
component = "todo"

[component.todo]
source = "todo.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.todo.build]
command = "./build.sh"
watch = ["src/**/*", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "fs"

[component.fs]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
files = [{ source = "static", destination = "/" }]